version: '3'

services:
  mySQLlamp:
    image: mysql:5.7
    container_name: mySQL-lamp
    volumes:
      - ./mySQLdata:/var/lib/mysql:z
    environment:
     - MYSQL_ROOT_PASSWORD=my5QLpAssw0rd
     - MYSQL_DATABASE=opensalesinventory

  websvrlamp:
    build: ./
    container_name: websvr-lamp
    volumes:
     - ./Work:/var/www/html:z
    ports:
     - 8001:80
    links:
     - mySQLlamp
    depends_on:
     - mySQLlamp

  phpmyadminlamp:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-lamp
    environment:
      - PMA_HOST=mySQLlamp
      - MYSQL_ROOT_PASSWORD=my5QLpAssw0rd
      - PMA_PORT=3306
    ports:
      - 8081:80
